In [3]:
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_502779f5d92d4e2788b57800a11e2285 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='_HEeQWoWfNxd-QbLJMGnegXBcrgBpJ8qm4-3n1XyWbW_',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_502779f5d92d4e2788b57800a11e2285.get_object(Bucket='assignment3-donotdelete-pr-j3ijjkm6on7k9s',Key='Oscars-demographics-DFE.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body, encoding='latin-1')
df.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,award,biourl,birthplace_gold,date_of_birth_gold,movie,person,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
0,670454353,False,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,Two Arabian Knights,Lewis Milestone,NaN,NaN,NaN,NaN
1,670454354,False,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1.0,2-Feb-1886,1.0,White,...,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,The Divine Lady,Frank Lloyd,NaN,NaN,NaN,NaN
2,670454355,False,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,All Quiet on the Western Front,Lewis Milestone,NaN,NaN,NaN,NaN
3,670454356,False,finalized,3,2/10/15 2:04,"Chicago, Il",1.0,23-Feb-1899,1.0,White,...,Best Director,http://www.nndb.com/people/544/000041421/,NaN,NaN,Skippy,Norman Taurog,NaN,NaN,NaN,NaN
4,670454357,False,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1.0,23-Apr-1894,1.0,White,...,Best Director,http://www.nndb.com/people/292/000044160/,NaN,NaN,Bad Girl,Frank Borzage,NaN,NaN,NaN,NaN

In [23]:
#Printing out the entire data
print(df)

      _unit_id  _golden _unit_state  _trusted_judgments _last_judgment_at  \
0    670454353    False   finalized                   3      2/10/15 3:45
1    670454354    False   finalized                   3      2/10/15 2:03
2    670454355    False   finalized                   3      2/10/15 2:05
3    670454356    False   finalized                   3      2/10/15 2:04
4    670454357    False   finalized                   3      2/10/15 1:48
5    670454358    False   finalized                   3      2/10/15 3:50
6    670454359    False   finalized                   3      2/10/15 2:07
7    670454360    False   finalized                   3      2/10/15 1:46
8    670454361    False   finalized                   3      2/10/15 1:47
9    670454362    False   finalized                   3      2/10/15 2:05
10   670454363    False   finalized                   3      2/10/15 2:04
11   670454364    False   finalized                   3      2/10/15 2:10
12   670454365    False   finalized                   3      2/10/15 2:12
13   670454366    False   finalized                   3      2/10/15 2:02
14   670454367    False   finalized                   3      2/10/15 3:57
15   670454368    False   finalized                   3      2/10/15 2:02
16   670454369    False   finalized                   3      2/10/15 2:29
17   670454370    False   finalized                   3      2/10/15 1:55
18   670454371    False   finalized                   3      2/10/15 4:02
19   670454372    False   finalized                   3      2/10/15 2:12
20   670454373    False   finalized                   3      2/10/15 1:46
21   670454374     True      golden                  82               NaN
22   670454375    False   finalized                   3      2/10/15 3:50
23   670454376    False   finalized                   3      2/10/15 1:51
24   670454377    False   finalized                   3      2/10/15 2:15
25   670454378    False   finalized                   3      2/10/15 2:15
26   670454379    False   finalized                   3      2/10/15 1:57
27   670454380    False   finalized                   3      2/10/15 3:50
28   670454381    False   finalized                   3      2/10/15 3:53
29   670454382    False   finalized                   3      2/10/15 3:50
..         ...      ...         ...                 ...               ...
411  670454764     True      golden                  86               NaN
412  670454765    False   finalized                   3      2/10/15 1:56
413  670454766    False   finalized                   3      2/10/15 2:18
414  670454767    False   finalized                   3      2/10/15 2:18
415  670454768    False   finalized                   3      2/10/15 2:10
416  670927629    False   finalized                   3      2/10/15 2:02
417  670939613    False   finalized                   3      2/10/15 1:53
418  670944094    False   finalized                   3      2/10/15 2:18
419  670944168    False   finalized                   3      2/10/15 3:55
420  670944316    False   finalized                   3      2/10/15 2:05
421  670944478    False   finalized                   3      2/10/15 1:49
422  670944543    False   finalized                   3      2/10/15 2:12
423  670944623    False   finalized                   3      2/10/15 2:11
424  670944674    False   finalized                   3      2/10/15 2:05
425  670944755    False   finalized                   3      2/10/15 2:04
426  670944822    False   finalized                   3      2/10/15 4:14
427  670944835    False   finalized                   3      2/10/15 2:08
428  670944920    False   finalized                   3      2/10/15 3:58
429  670944948    False   finalized                   3      2/10/15 2:06
430  670945043     True      golden                  86               NaN
431  670945693    False   finalized                   3      2/10/15 1:49
432  670945790    False   finalized                   3      2/10/15 2:08
433  670945834    False   finalized                   3      2/10/15 2:07
434  670945895    False   finalized                   3      2/10/15 2:13
435  670946199    False   finalized                   3      2/10/15 2:03
436  670946276    False   finalized                   3      2/10/15 2:00
437  670946299    False   finalized                   3      2/10/15 2:04
438  670964912    False   finalized                   3      2/10/15 2:03
439  670964956    False   finalized                   3      2/10/15 2:01
440  670972898    False   finalized                   3      2/10/15 2:01

                              birthplace  birthplace:confidence date_of_birth  \
0                      Chisinau, Moldova                 1.0000   30-Sep-1895
1                      Glasgow, Scotland                 1.0000    2-Feb-1886
2                      Chisinau, Moldova                 1.0000   30-Sep-1895
3                            Chicago, Il                 1.0000   23-Feb-1899
4                     Salt Lake City, Ut                 1.0000   23-Apr-1894
5                      Glasgow, Scotland                 1.0000    2-Feb-1886
6              Bisacquino, Sicily, Italy                 1.0000   18-May-1897
7                     Cape Elizabeth, Me                 1.0000    1-Feb-1894
8              Bisacquino, Sicily, Italy                 1.0000   18-May-1897
9                        Los Angeles, Ca                 1.0000    3-Oct-1898
10             Bisacquino, Sicily, Italy                 1.0000   18-May-1897
11                          Pasadena, Ca                 1.0000   23-Feb-1883
12                    Cape Elizabeth, Me                 1.0000    1-Feb-1894
13                    Cape Elizabeth, Me                 1.0000    1-Feb-1894
14   Mulhouse, Haut-Rhin, Alsace, France                 1.0000    1-Jul-1902
15                     Budapest, Hungary                 1.0000   24-Dec-1886
16                       Los Angeles, Ca                 1.0000    3-Oct-1898
17                         New York City                 1.0000     11-Oct-18
18               Sucha, Galicia, Austria                 0.6667     22-Jun-06
19   Mulhouse, Haut-Rhin, Alsace, France                 1.0000    1-Jul-1902
20                      Istanbul, Turkey                 1.0000      7-Sep-09
21                            Nevada, Mo                 1.0000      5-Aug-06
22                      Wilkes-Barre, Pa                 1.0000     11-Feb-09
23                      Wilkes-Barre, Pa                 1.0000     11-Feb-09
24                           Oakland, Ca                 1.0000     18-Dec-04
25                    Cape Elizabeth, Me                 1.0000    1-Feb-1894
26                       Vienna, Austria                 1.0000     29-Apr-07
27                      Istanbul, Turkey                 1.0000      7-Sep-09
28                          Lawrence, Ks                 1.0000     30-Jan-20
29                           Oakland, Ca                 1.0000     18-Dec-04
..                                   ...                    ...           ...
411                         Woodlawn, Md                 1.0000     11-Dec-67
412                        New York City                 1.0000     14-Sep-60
413                       Montgomery, Al                 1.0000     25-May-72
414                         Brooklyn, Ny                 1.0000     12-Nov-82
415                  Mexico City, Mexico                 1.0000      1-Mar-83
416              Sucha, Galicia, Austria                 1.0000     22-Jun-06
417                     Independence, Mo                 1.0000     16-Jul-11
418                          Concord, Ca                 1.0000      9-Jul-56
419                        New York City                 1.0000      3-Feb-39
420                           Quincy, Il                 1.0000      3-May-06
421                      Los Angeles, Ca                 1.0000      4-Jun-75
422                        New York City                 1.0000     31-Oct-27
423                        New York City                 1.0000   25-Jun-1903
424                           Bascom, Fl                 1.0000     14-Jan-41
425                          Walters, Ok                 1.0000     13-Dec-10
426                      Thomasville, Ga                 1.0000     27-Feb-30
427                           Helena, Mt                 1.0000    7-May-1901
428                      London, England                 1.0000     27-Feb-32
429                          Lincoln, Ne                 1.0000     30-Jul-74
430                          Lincoln, Ne                 1.0000     30-Jul-74
431                      Los Angeles, Ca                 1.0000     27-Sep-72
432                           Malden, Ma                 1.0000     16-Jun-07
433                         Woodlawn, Md                 1.0000     11-Dec-67
434                         La Jolla, Ca                 1.0000     14-Aug-59
435               Ilford, Essex, England                 1.0000     28-Dec-34
436                      London, England                 1.0000      7-Mar-71
437                  Manchester, England                 1.0000     20-Oct-56
438                          Chicago, Il                 1.0000     26-Jul-22
439                           Laurel, Ne                 1.0000     31-Aug-28
440                           Nevada, Mo                 1.0000      5-Aug-06

     date_of_birth:confidence race_ethnicity  ...                    award  \
0                      1.0000          White  ...            Best Director
1                      1.0000          White  ...            Best Director
2                      1.0000          White  ...            Best Director
3                      1.0000          White  ...            Best Director
4                      1.0000          White  ...            Best Director
5                      1.0000          White  ...            Best Director
6                      1.0000          White  ...            Best Director
7                      1.0000          White  ...            Best Director
8                      1.0000          White  ...            Best Director
9                      1.0000          White  ...            Best Director
10                     1.0000          White  ...            Best Director
11                     1.0000          White  ...            Best Director
12                     1.0000          White  ...            Best Director
13                     1.0000          White  ...            Best Director
14                     1.0000          White  ...            Best Director
15                     1.0000          White  ...            Best Director
16                     1.0000          White  ...            Best Director
17                     1.0000          White  ...            Best Director
18                     1.0000          White  ...            Best Director
19                     1.0000          White  ...            Best Director
20                     1.0000          White  ...            Best Director
21                     1.0000          White  ...            Best Director
22                     1.0000          White  ...            Best Director
23                     1.0000          White  ...            Best Director
24                     1.0000          White  ...            Best Director
25                     1.0000          White  ...            Best Director
26                     1.0000          White  ...            Best Director
27                     1.0000          White  ...            Best Director
28                     1.0000          White  ...            Best Director
29                     1.0000          White  ...            Best Director
..                        ...            ...  ...                      ...
411                    0.9631          Black  ...  Best Supporting Actress
412                    1.0000          White  ...  Best Supporting Actress
413                    1.0000          Black  ...  Best Supporting Actress
414                    1.0000          White  ...  Best Supporting Actress
415                    1.0000          Black  ...  Best Supporting Actress
416                    1.0000          White  ...            Best Director
417                    1.0000          White  ...             Best Actress
418                    1.0000          White  ...               Best Actor
419                    1.0000          White  ...            Best Director
420                    1.0000          White  ...  Best Supporting Actress
421                    1.0000          White  ...  Best Supporting Actress
422                    1.0000          White  ...  Best Supporting Actress
423                    1.0000          White  ...  Best Supporting Actress
424                    1.0000          White  ...             Best Actress
425                    1.0000          White  ...    Best Supporting Actor
426                    1.0000          White  ...             Best Actress
427                    1.0000          White  ...               Best Actor
428                    1.0000          White  ...             Best Actress
429                    1.0000          White  ...             Best Actress
430                    1.0000          White  ...             Best Actress
431                    1.0000          White  ...             Best Actress
432                    1.0000          White  ...    Best Supporting Actor
433                    1.0000          Black  ...  Best Supporting Actress
434                    1.0000          White  ...  Best Supporting Actress
435                    1.0000          White  ...             Best Actress
436                    1.0000          White  ...  Best Supporting Actress
437                    1.0000          White  ...            Best Director
438                    1.0000          White  ...    Best Supporting Actor
439                    1.0000          White  ...    Best Supporting Actor
440                    1.0000          White  ...            Best Director

                                        biourl  birthplace_gold  \
0    http://www.nndb.com/people/320/000043191/              NaN
1    http://www.nndb.com/people/626/000042500/              NaN
2    http://www.nndb.com/people/320/000043191/              NaN
3    http://www.nndb.com/people/544/000041421/              NaN
4    http://www.nndb.com/people/292/000044160/              NaN
5    http://www.nndb.com/people/626/000042500/              NaN
6    http://www.nndb.com/people/459/000032363/              NaN
7    http://www.nndb.com/people/458/000032362/              NaN
8    http://www.nndb.com/people/459/000032363/              NaN
9    http://www.nndb.com/people/380/000044248/              NaN
10   http://www.nndb.com/people/459/000032363/              NaN
11   http://www.nndb.com/people/416/000041293/              NaN
12   http://www.nndb.com/people/458/000032362/              NaN
13   http://www.nndb.com/people/458/000032362/              NaN
14   http://www.nndb.com/people/463/000032367/              NaN
15   http://www.nndb.com/people/676/000032580/              NaN
16   http://www.nndb.com/people/380/000044248/              NaN
17   http://www.nndb.com/people/281/000064089/              NaN
18   http://www.nndb.com/people/982/000024910/              NaN
19   http://www.nndb.com/people/463/000032367/              NaN
20   http://www.nndb.com/people/537/000026459/              NaN
21   http://www.nndb.com/people/704/000024632/              NaN
22   http://www.nndb.com/people/723/000032627/              NaN
23   http://www.nndb.com/people/723/000032627/              NaN
24   http://www.nndb.com/people/382/000044250/              NaN
25   http://www.nndb.com/people/458/000032362/              NaN
26   http://www.nndb.com/people/538/000032442/              NaN
27   http://www.nndb.com/people/537/000026459/              NaN
28   http://www.nndb.com/people/384/000044252/              NaN
29   http://www.nndb.com/people/382/000044250/              NaN
..                                         ...              ...
411  http://www.nndb.com/people/836/000131443/              NaN
412  http://www.nndb.com/people/327/000042201/              NaN
413  http://www.nndb.com/people/304/000281458/              NaN
414  http://www.nndb.com/people/220/000032124/              NaN
415  http://www.nndb.com/people/570/000380427/              NaN
416  http://www.nndb.com/people/982/000024910/              NaN
417  http://www.nndb.com/people/635/000043506/              NaN
418  http://www.nndb.com/people/687/000022621/              NaN
419  http://www.nndb.com/people/810/000043681/              NaN
420  http://www.nndb.com/people/690/000042564/              NaN
421  http://www.nndb.com/people/493/000023424/              NaN
422  http://www.nndb.com/people/409/000032313/              NaN
423  http://www.nndb.com/people/081/000063889/              NaN
424  http://www.nndb.com/people/884/000022818/              NaN
425  http://www.nndb.com/people/680/000042554/              NaN
426  http://www.nndb.com/people/747/000043618/              NaN
427  http://www.nndb.com/people/740/000031647/              NaN
428  http://www.nndb.com/people/624/000023555/              NaN
429  http://www.nndb.com/people/333/000026255/              NaN
430  http://www.nndb.com/people/333/000026255/              NaN
431  http://www.nndb.com/people/592/000023523/              NaN
432  http://www.nndb.com/people/559/000049412/              NaN
433  http://www.nndb.com/people/836/000131443/              NaN
434  http://www.nndb.com/people/641/000025566/              NaN
435  http://www.nndb.com/people/260/000030170/              NaN
436  http://www.nndb.com/people/309/000032213/              NaN
437  http://www.nndb.com/people/887/000044755/              NaN
438  http://www.nndb.com/people/224/000032128/              NaN
439  http://www.nndb.com/people/764/000022698/              NaN
440  http://www.nndb.com/people/704/000024632/              NaN

    date_of_birth_gold                             movie  \
0                  NaN               Two Arabian Knights
1                  NaN                   The Divine Lady
2                  NaN    All Quiet on the Western Front
3                  NaN                            Skippy
4                  NaN                          Bad Girl
5                  NaN                         Cavalcade
6                  NaN             It Happened One Night
7                  NaN                      The Informer
8                  NaN            Mr. Deeds Goes to Town
9                  NaN                   The Awful Truth
10                 NaN        You Can't Take It with You
11                 NaN                Gone with the Wind
12                 NaN               The Grapes of Wrath
13                 NaN           How Green Was My Valley
14                 NaN                      Mrs. Miniver
15                 NaN                        Casablanca
16                 NaN                      Going My Way
17                 NaN                   West Side Story
18                 NaN                  The Lost Weekend
19                 NaN       The Best Years of Our Lives
20                 NaN             Gentleman's Agreement
21            5-Aug-06  The Treasure of the Sierra Madre
22                 NaN           A Letter to Three Wives
23                 NaN                     All About Eve
24                 NaN                A Place in the Sun
25                 NaN                     The Quiet Man
26                 NaN             From Here to Eternity
27                 NaN                 On the Waterfront
28                 NaN                             Marty
29                 NaN                             Giant
..                 ...                               ...
411          11-Dec-67                          Precious
412                NaN                       The Fighter

In [41]:
#Describing the data
df.describe()

,_unit_id,_trusted_judgments,birthplace:confidence,date_of_birth:confidence,race_ethnicity:confidence,religion:confidence,sexual_orientation:confidence,year_of_award,year_of_award:confidence,year_of_award_gold
count,4.410000e+02,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,11.000000
mean,6.704825e+08,7.637188,0.995259,0.996607,0.999130,0.989373,0.992390,1973.165533,0.990082,1977.363636
std,1.139974e+05,19.015541,0.038917,0.032060,0.016438,0.065610,0.049458,24.030895,0.059177,21.592928
min,6.704544e+08,3.000000,0.657100,0.656200,0.657100,0.333300,0.657100,1927.000000,0.333300,1942.000000
25%,6.704545e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1953.000000,1.000000,1964.000000
50%,6.704546e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1973.000000,1.000000,1977.000000
75%,6.704547e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1994.000000,1.000000,1997.000000
max,6.709729e+08,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,2006.000000

In [24]:
#Printing out the types for each attributes
print(df.dtypes)

_unit_id                           int64
_golden                             bool
_unit_state                       object
_trusted_judgments                 int64
_last_judgment_at                 object
birthplace                        object
birthplace:confidence            float64
date_of_birth                     object
date_of_birth:confidence         float64
race_ethnicity                    object
race_ethnicity:confidence        float64
religion                          object
religion:confidence              float64
sexual_orientation                object
sexual_orientation:confidence    float64
year_of_award                      int64
year_of_award:confidence         float64
award                             object
biourl                            object
birthplace_gold                   object
date_of_birth_gold                object
movie                             object
person                            object
race_ethnicity_gold               object
religion_gold                     object
sexual_orientation_gold           object
year_of_award_gold               float64
dtype: object

In [25]:
#Printing out the shape of the dataframe
print('Dataframe Shape: ', df.shape)

Dataframe Shape:  (441, 27)

In [26]:
#Checking for missing values
print('null values: ', df.isnull())

null values:       _unit_id  _golden  _unit_state  _trusted_judgments  _last_judgment_at  \
0       False    False        False               False              False
1       False    False        False               False              False
2       False    False        False               False              False
3       False    False        False               False              False
4       False    False        False               False              False
5       False    False        False               False              False
6       False    False        False               False              False
7       False    False        False               False              False
8       False    False        False               False              False
9       False    False        False               False              False
10      False    False        False               False              False
11      False    False        False               False              False
12      False    False        False               False              False
13      False    False        False               False              False
14      False    False        False               False              False
15      False    False        False               False              False
16      False    False        False               False              False
17      False    False        False               False              False
18      False    False        False               False              False
19      False    False        False               False              False
20      False    False        False               False              False
21      False    False        False               False               True
22      False    False        False               False              False
23      False    False        False               False              False
24      False    False        False               False              False
25      False    False        False               False              False
26      False    False        False               False              False
27      False    False        False               False              False
28      False    False        False               False              False
29      False    False        False               False              False
..        ...      ...          ...                 ...                ...
411     False    False        False               False               True
412     False    False        False               False              False
413     False    False        False               False              False
414     False    False        False               False              False
415     False    False        False               False              False
416     False    False        False               False              False
417     False    False        False               False              False
418     False    False        False               False              False
419     False    False        False               False              False
420     False    False        False               False              False
421     False    False        False               False              False
422     False    False        False               False              False
423     False    False        False               False              False
424     False    False        False               False              False
425     False    False        False               False              False
426     False    False        False               False              False
427     False    False        False               False              False
428     False    False        False               False              False
429     False    False        False               False              False
430     False    False        False               False               True
431     False    False        False               False              False
432     False    False        False               False              False
433     False    False        False               False              False
434     False    False        False               False              False
435     False    False        False               False              False
436     False    False        False               False              False
437     False    False        False               False              False
438     False    False        False               False              False
439     False    False        False               False              False
440     False    False        False               False              False

     birthplace  birthplace:confidence  date_of_birth  \
0         False                  False          False
1         False                  False          False
2         False                  False          False
3         False                  False          False
4         False                  False          False
5         False                  False          False
6         False                  False          False
7         False                  False          False
8         False                  False          False
9         False                  False          False
10        False                  False          False
11        False                  False          False
12        False                  False          False
13        False                  False          False
14        False                  False          False
15        False                  False          False
16        False                  False          False
17        False                  False          False
18        False                  False          False
19        False                  False          False
20        False                  False          False
21        False                  False          False
22        False                  False          False
23        False                  False          False
24        False                  False          False
25        False                  False          False
26        False                  False          False
27        False                  False          False
28        False                  False          False
29        False                  False          False
..          ...                    ...            ...
411       False                  False          False
412       False                  False          False
413       False                  False          False
414       False                  False          False
415       False                  False          False
416       False                  False          False
417       False                  False          False
418       False                  False          False
419       False                  False          False
420       False                  False          False
421       False                  False          False
422       False                  False          False
423       False                  False          False
424       False                  False          False
425       False                  False          False
426       False                  False          False
427       False                  False          False
428       False                  False          False
429       False                  False          False
430       False                  False          False
431       False                  False          False
432       False                  False          False
433       False                  False          False
434       False                  False          False
435       False                  False          False
436       False                  False          False
437       False                  False          False
438       False                  False          False
439       False                  False          False
440       False                  False          False

     date_of_birth:confidence  race_ethnicity  ...  award  biourl  \
0                       False           False  ...  False   False
1                       False           False  ...  False   False
2                       False           False  ...  False   False
3                       False           False  ...  False   False
4                       False           False  ...  False   False
5                       False           False  ...  False   False
6                       False           False  ...  False   False
7                       False           False  ...  False   False
8                       False           False  ...  False   False
9                       False           False  ...  False   False
10                      False           False  ...  False   False
11                      False           False  ...  False   False
12                      False           False  ...  False   False
13                      False           False  ...  False   False
14                      False           False  ...  False   False
15                      False           False  ...  False   False
16                      False           False  ...  False   False
17                      False           False  ...  False   False
18                      False           False  ...  False   False
19                      False           False  ...  False   False
20                      False           False  ...  False   False
21                      False           False  ...  False   False
22                      False           False  ...  False   False
23                      False           False  ...  False   False
24                      False           False  ...  False   False
25                      False           False  ...  False   False
26                      False           False  ...  False   False
27                      False           False  ...  False   False
28                      False           False  ...  False   False
29                      False           False  ...  False   False
..                        ...             ...  ...    ...     ...
411                     False           False  ...  False   False
412                     False           False  ...  False   False
413                     False           False  ...  False   False
414                     False           False  ...  False   False
415                     False           False  ...  False   False
416                     False           False  ...  False   False
417                     False           False  ...  False   False
418                     False           False  ...  False   False
419                     False           False  ...  False   False
420                     False           False  ...  False   False
421                     False           False  ...  False   False
422                     False           False  ...  False   False
423                     False           False  ...  False   False
424                     False           False  ...  False   False
425                     False           False  ...  False   False
426                     False           False  ...  False   False
427                     False           False  ...  False   False
428                     False           False  ...  False   False
429                     False           False  ...  False   False
430                     False           False  ...  False   False
431                     False           False  ...  False   False
432                     False           False  ...  False   False
433                     False           False  ...  False   False
434                     False           False  ...  False   False
435                     False           False  ...  False   False
436                     False           False  ...  False   False
437                     False           False  ...  False   False
438                     False           False  ...  False   False
439                     False           False  ...  False   False
440                     False           False  ...  False   False

     birthplace_gold  date_of_birth_gold  movie  person  race_ethnicity_gold  \
0               True                True  False   False                 True
1               True                True  False   False                 True
2               True                True  False   False                 True
3               True                True  False   False                 True
4               True                True  False   False                 True
5               True                True  False   False                 True
6               True                True  False   False                 True
7               True                True  False   False                 True
8               True                True  False   False                 True
9               True                True  False   False                 True
10              True                True  False   False                 True
11              True                True  False   False                 True
12              True                True  False   False                 True
13              True                True  False   False                 True
14              True                True  False   False                 True
15              True                True  False   False                 True
16              True                True  False   False                 True
17              True                True  False   False                 True
18              True                True  False   False                 True
19              True                True  False   False                 True
20              True                True  False   False                 True
21              True               False  False   False                 True
22              True                True  False   False                 True
23              True                True  False   False                 True
24              True                True  False   False                 True
25              True                True  False   False                 True
26              True                True  False   False                 True
27              True                True  False   False                 True
28              True                True  False   False                 True
29              True                True  False   False                 True
..               ...                 ...    ...     ...                  ...
411             True               False  False   False                False
412             True                True  False   False                 True
413             True                True  False   False                 True
414             True                True  False   False                 True
415             True                True  False   False                 True
416             True                True  False   False                 True
417             True                True  False   False                 True
418             True                True  False   False                 True
419             True                True  False   False                 True
420             True                True  False   False                 True
421             True                True  False   False                 True
422             True                True  False   False                 True
423             True                True  False   False                 True
424             True                True  False   False                 True
425             True                True  False   False                 True
426             True                True  False   False                 True
427             True                True  False   False                 True
428             True                True  False   False                 True
429             True                True  False   False                 True
430             True                True  False   False                 True
431             True                True  False   False                 True
432             True                True  False   False                 True
433             True                True  False   False                 True
434             True                True  False   False                 True
435             True                True  False   False                 True
436             True                True  False   False                 True
437             True                True  False   False                 True
438             True                True  False   False                 True
439             True                True  False   False                 True
440             True                True  False   False                 True

     religion_gold  sexual_orientation_gold  year_of_award_gold
0             True                     True                True
1             True                     True                True
2             True                     True                True
3             True                     True                True
4             True                     True                True
5             True                     True                True
6             True                     True                True
7             True                     True                True
8             True                     True                True
9             True                     True                True
10            True                     True                True
11            True                     True                True
12            True                     True                True
13            True                     True                True
14            True                     True                True
15            True                     True                True
16            True                     True                True
17            True                     True                True
18            True                     True                True
19            True                     True                True
20            True                     True                True
21            True                     True                True
22            True                     True                True
23            True                     True                True
24            True                     True                True
25            True                     True                True
26            True                     True                True
27            True                     True                True
28            True                     True                True
29            True                     True                True
..             ...                      ...                 ...
411           True                     True                True
412           True                     True                True
413           True                     True                True
414           True                     True                True
415           True                     True                True
416           True                     True                True
417           True                     True                True
418           True                     True                True
419           True                     True                True
420           True                     True                True
421           True                     True                True
422           True                     True                True
423           True                     True                True
424           True                     True                True
425           True                     True                True
426           True                     True                True

In [27]:
#Checking the sum of missing values
print(df.isnull().sum())

_unit_id                           0
_golden                            0
_unit_state                        0
_trusted_judgments                 0
_last_judgment_at                 25
birthplace                         0
birthplace:confidence              0
date_of_birth                      0
date_of_birth:confidence           0
race_ethnicity                     0
race_ethnicity:confidence          0
religion                           0
religion:confidence                0
sexual_orientation                 0
sexual_orientation:confidence      0
year_of_award                      0
year_of_award:confidence           0
award                              0
biourl                             0
birthplace_gold                  432
date_of_birth_gold               433
movie                              0
person                             0
race_ethnicity_gold              439
religion_gold                    431
sexual_orientation_gold          438
year_of_award_gold               430
dtype: int64

In [29]:
#Check for total missing values
print('Total missing values: ', df.isnull().sum().sum())

Total missing values:  2628

In [11]:
#Removing attributes with little to no values
new_df = df.drop(['birthplace_gold', 'date_of_birth_gold', 'race_ethnicity_gold', 'religion_gold', 'sexual_orientation_gold', 'year_of_award_gold'], axis=1)
print(new_df.shape)

(441, 21)

In [12]:
#Describing new dataframe
new_df.describe()

,_unit_id,_trusted_judgments,birthplace:confidence,date_of_birth:confidence,race_ethnicity:confidence,religion:confidence,sexual_orientation:confidence,year_of_award,year_of_award:confidence
count,4.410000e+02,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000
mean,6.704825e+08,7.637188,0.995259,0.996607,0.999130,0.989373,0.992390,1973.165533,0.990082
std,1.139974e+05,19.015541,0.038917,0.032060,0.016438,0.065610,0.049458,24.030895,0.059177
min,6.704544e+08,3.000000,0.657100,0.656200,0.657100,0.333300,0.657100,1927.000000,0.333300
25%,6.704545e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1953.000000,1.000000
50%,6.704546e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1973.000000,1.000000
75%,6.704547e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1994.000000,1.000000
max,6.709729e+08,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2014.000000,1.000000

In [13]:
#New Dataframe
new_df.head(441)

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,religion,religion:confidence,sexual_orientation,sexual_orientation:confidence,year_of_award,year_of_award:confidence,award,biourl,movie,person
0,670454353,False,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1.0000,30-Sep-1895,1.0000,White,...,Na,1.0,Straight,1.0000,1927,1.0000,Best Director,http://www.nndb.com/people/320/000043191/,Two Arabian Knights,Lewis Milestone
1,670454354,False,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1.0000,2-Feb-1886,1.0000,White,...,Na,1.0,Straight,0.6842,1930,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,The Divine Lady,Frank Lloyd
2,670454355,False,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1.0000,30-Sep-1895,1.0000,White,...,Na,1.0,Straight,1.0000,1931,0.6667,Best Director,http://www.nndb.com/people/320/000043191/,All Quiet on the Western Front,Lewis Milestone
3,670454356,False,finalized,3,2/10/15 2:04,"Chicago, Il",1.0000,23-Feb-1899,1.0000,White,...,Na,1.0,Straight,1.0000,1932,1.0000,Best Director,http://www.nndb.com/people/544/000041421/,Skippy,Norman Taurog
4,670454357,False,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1.0000,23-Apr-1894,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1933,1.0000,Best Director,http://www.nndb.com/people/292/000044160/,Bad Girl,Frank Borzage
5,670454358,False,finalized,3,2/10/15 3:50,"Glasgow, Scotland",1.0000,2-Feb-1886,1.0000,White,...,Na,1.0,Straight,1.0000,1934,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,Cavalcade,Frank Lloyd
6,670454359,False,finalized,3,2/10/15 2:07,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1935,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,It Happened One Night,Frank Capra
7,670454360,False,finalized,3,2/10/15 1:46,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1936,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,The Informer,John Ford
8,670454361,False,finalized,3,2/10/15 1:47,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1937,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,Mr. Deeds Goes to Town,Frank Capra
9,670454362,False,finalized,3,2/10/15 2:05,"Los Angeles, Ca",1.0000,3-Oct-1898,1.0000,White,...,Na,1.0,Straight,1.0000,1938,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,The Awful Truth,Leo McCarey
10,670454363,False,finalized,3,2/10/15 2:04,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1939,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,You Can't Take It with You,Frank Capra
11,670454364,False,finalized,3,2/10/15 2:10,"Pasadena, Ca",1.0000,23-Feb-1883,1.0000,White,...,Na,1.0,Straight,1.0000,1940,1.0000,Best Director,http://www.nndb.com/people/416/000041293/,Gone with the Wind,Victor Fleming
12,670454365,False,finalized,3,2/10/15 2:12,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1941,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,The Grapes of Wrath,John Ford
13,670454366,False,finalized,3,2/10/15 2:02,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1942,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,How Green Was My Valley,John Ford
14,670454367,False,finalized,3,2/10/15 3:57,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,1.0000,White,...,Na,1.0,Straight,1.0000,1943,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,Mrs. Miniver,William Wyler
15,670454368,False,finalized,3,2/10/15 2:02,"Budapest, Hungary",1.0000,24-Dec-1886,1.0000,White,...,Na,1.0,Straight,1.0000,1944,1.0000,Best Director,http://www.nndb.com/people/676/000032580/,Casablanca,Michael Curtiz
16,670454369,False,finalized,3,2/10/15 2:29,"Los Angeles, Ca",1.0000,3-Oct-1898,1.0000,White,...,Na,1.0,Straight,1.0000,1945,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,Going My Way,Leo McCarey
17,670454370,False,finalized,3,2/10/15 1:55,New York City,1.0000,11-Oct-18,1.0000,White,...,Jewish,1.0,Gay,1.0000,1962,1.0000,Best Director,http://www.nndb.com/people/281/000064089/,West Side Story,Jerome Robbins
18,670454371,False,finalized,3,2/10/15 4:02,"Sucha, Galicia, Austria",0.6667,22-Jun-06,1.0000,White,...,Jewish,1.0,Straight,1.0000,1946,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,The Lost Weekend,Billy Wilder
19,670454372,False,finalized,3,2/10/15 2:12,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,1.0000,White,...,Na,1.0,Straight,1.0000,1947,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,The Best Years of Our Lives,William Wyler
20,670454373,False,finalized,3,2/10/15 1:46,"Istanbul, Turkey",1.0000,7-Sep-09,1.0000,White,...,Na,1.0,Straight,1.0000,1948,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,Gentleman's Agreement,Elia Kazan
21,670454374,True,golden,82,NaN,"Nevada, Mo",1.0000,5-Aug-06,1.0000,White,...,Na,1.0,Straight,1.0000,1949,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,The Treasure of the Sierra Madre,John Huston
22,670454375,False,finalized,3,2/10/15 3:50,"Wilkes-Barre, Pa",1.0000,11-Feb-09,1.0000,White,...,Jewish,1.0,Straight,1.0000,1950,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,A Letter to Three Wives,Joseph L. Mankiewicz
23,670454376,False,finalized,3,2/10/15 1:51,"Wilkes-Barre, Pa",1.0000,11-Feb-09,1.0000,White,...,Jewish,1.0,Straight,1.0000,1951,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,All About Eve,Joseph L. Mankiewicz
24,670454377,False,finalized,3,2/10/15 2:15,"Oakland, Ca",1.0000,18-Dec-04,1.0000,White,...,Na,1.0,Straight,1.0000,1952,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,A Place in the Sun,George Stevens
25,670454378,False,finalized,3,2/10/15 2:15,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1953,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,The Quiet Man,John Ford
26,670454379,False,finalized,3,2/10/15 1:57,"Vienna, Austria",1.0000,29-Apr-07,1.0000,White,...,Jewish,1.0,Straight,1.0000,1954,1.0000,Best Director,http://www.nndb.com/people/538/000032442/,From Here to Eternity,Fred Zinnemann
27,670454380,False,finalized,3,2/10/15 3:50,"Istanbul, Turkey",1.0000,7-Sep-09,1.0000,White,...,Na,1.0,Straight,1.0000,1955,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,On the Waterfront,Elia Kazan
28,670454381,False,finalized,3,2/10/15 3:53,"Lawrence, Ks",1.0000,30-Jan-20,1.0000,White,...,Presbyterian,1.0,Straight,1.0000,1956,1.0000,Best Director,http://www.nndb.com/people/384/000044252/,Marty,Delbert Mann
29,670454382,False,finalized,3,2/10/15 3:50,"Oakland, Ca",1.0000,18-Dec-04,1.0000,White,...,Na,1.0,Straight,1.0000,1957,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,670454764,True,golden,86,NaN,"Woodlawn, Md",1.0000,11-Dec-67,0.9631,Black,...,Na,1.0,Straight,1.0000,2010,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,Precious,Mo'Nique
412,670454765,False,finalized,3,2/10/15 1:56,New York City,1.0000,14-Sep-60,1.0000,White,...,Na,1.0,Straight,1.0000,2011,1.0000,Best Supporting Actress,http://www.nndb.com/people/327/000042201/,The Fighter,Melissa Leo
413,670454766,False,finalized,3,2/10/15 2:18,"Montgomery, Al",1.0000,25-May-72,1.0000,Black,...,Na,1.0,Na,1.0000,2012,1.0000,Best Supporting Actress,http://www.nndb.com/people/304/000281458/,The Help,Octavia Spencer
414,670454767,False,finalized,3,2/10/15 2:18,"Brooklyn, Ny",1.0000,12-Nov-82,1.0000,White,...,Christian,1.0,Straight,1.0000,2013,1.0000,Best Supporting Actress,http://www.nndb.com/people/220/000032124/,Les MisÃŒÂ©rables,Anne Hathaway
415,670454768,False,finalized,3,2/10/15 2:10,"Mexico City, Mexico",1.0000,1-Mar-83,1.0000,Black,...,Na,1.0,Na,1.0000,2014,1.0000,Best Supporting Actress,http://www.nndb.com/people/570/000380427/,12 Years a Slave,Lupita Nyong'o
416,670927629,False,finalized,3,2/10/15 2:02,"Sucha, Galicia, Austria",1.0000,22-Jun-06,1.0000,White,...,Jewish,1.0,Straight,1.0000,1961,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,The Apartment,Billy Wilder
417,670939613,False,finalized,3,2/10/15 1:53,"Independence, Mo",1.0000,16-Jul-11,1.0000,White,...,Christian Science,1.0,Straight,1.0000,1941,1.0000,Best Actress,http://www.nndb.com/people/635/000043506/,Kitty Foyle,Ginger Rogers
418,670944094,False,finalized,3,2/10/15 2:18,"Concord, Ca",1.0000,9-Jul-56,1.0000,White,...,Born-Again Christian,1.0,Straight,1.0000,1994,1.0000,Best Actor,http://www.nndb.com/people/687/000022621/,Philadelphia,Tom Hanks
419,670944168,False,finalized,3,2/10/15 3:55,New York City,1.0000,3-Feb-39,1.0000,White,...,Na,1.0,Straight,1.0000,1979,0.6667,Best Director,http://www.nndb.com/people/810/000043681/,The Deer Hunter,Michael Cimino
420,670944316,False,finalized,3,2/10/15 2:05,"Quincy, Il",1.0000,3-May-06,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1942,1.0000,Best Supporting Actress,http://www.nndb.com/people/690/000042564/,The Great Lie,Mary Astor
421,670944478,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,4-Jun-75,1.0000,White,...,Buddhist,1.0,Bisexual,1.0000,2000,1.0000,Best Supporting Actress,http://www.nndb.com/people/493/000023424/,"Girl, Interrupted",Angelina Jolie
422,670944543,False,finalized,3,2/10/15 2:12,New York City,1.0000,31-Oct-27,1.0000,White,...,Jewish,1.0,Straight,1.0000,1976,1.0000,Best Supporting Actress,http://www.nndb.com/people/409/000032313/,Shampoo,Lee Grant
423,670944623,False,finalized,3,2/10/15 2:11,New York City,1.0000,25-Jun-1903,1.0000,White,...,Na,1.0,Straight,1.0000,1946,1.0000,Best Supporting Actress,http://www.nndb.com/people/081/000063889/,National Velvet,Anne Revere
424,670944674,False,finalized,3,2/10/15 2:05,"Bascom, Fl",1.0000,14-Jan-41,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1977,1.0000,Best Actress,http://www.nndb.com/people/884/000022818/,Network,Faye Dunaway
425,670944755,False,finalized,3,2/10/15 2:04,"Walters, Ok",1.0000,13-Dec-10,1.0000,White,...,Na,1.0,Straight,1.0000,1943,1.0000,Best Supporting Actor,http://www.nndb.com/people/680/000042554/,Johnny Eager,Van Heflin
426,670944822,False,finalized,3,2/10/15 4:14,"Thomasville, Ga",1.0000,27-Feb-30,1.0000,White,...,Na,1.0,Straight,1.0000,1958,1.0000,Best Actress,http://www.nndb.com/people/747/000043618/,The Three Faces of Eve,Joanne Woodward
427,670944835,False,finalized,3,2/10/15 2:08,"Helena, Mt",1.0000,7-May-1901,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1953,1.0000,Best Actor,http://www.nndb.com/people/740/000031647/,High Noon,Gary Cooper
428,670944920,False,finalized,3,2/10/15 3:58,"London, England",1.0000,27-Feb-32,1.0000,White,...,Jewish,1.0,Straight,1.0000,1967,1.0000,Best Actress,http://www.nndb.com/people/624/000023555/,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,670944948,False,finalized,3,2/10/15 2:06,"Lincoln, Ne",1.0000,30-Jul-74,1.0000,White,...,Na,1.0,Straight,1.0000,2005,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,Million Dollar Baby,Hilary Swank
430,670945043,True,golden,86,NaN,"Lincoln, Ne",1.0000,30-Jul-74,1.0000,White,...,Na,1.0,Straight,1.0000,2005,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,Million Dollar Baby,Hilary Swank
431,670945693,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,27-Sep-72,1.0000,White,...,Jewish,1.0,Straight,1.0000,1999,1.0000,Best Actress,http://www.nndb.com/people/592/000023523/,Shakespeare in Love,Gwyneth Paltrow
432,670945790,False,finalized,3,2/10/15 2:08,"Malden, Ma",1.0000,16-Jun-07,1.0000,White,...,Na,1.0,Na,1.0000,1969,1.0000,Best Supporting Actor,http://www.nndb.com/people/559/000049412/,The Subject Was Roses,Jack Albertson
433,670945834,False,finalized,3,2/10/15 2:07,"Woodlawn, Md",1.0000,11-Dec-67,1.0000,Black,...,Na,1.0,Straight,1.0000,2010,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,Precious,Mo'Nique
434,670945895,False,finalized,3,2/10/15 2:13,"La Jolla, Ca",1.0000,14-Aug-59,1.0000,White,...,Na,1.0,Straight,1.0000,2001,1.0000,Best Supporting Actress,http://www.nndb.com/people/641/000025566/,Pollock,Marcia Gay Harden
435,670946199,False,finalized,3,2/10/15 2:03,"Ilford, Essex, England",1.0000,28-Dec-34,1.0000,White,...,Na,1.0,Straight,1.0000,1970,1.0000,Best Actress,http://www.nndb.com/people/260/000030170/,The Prime of Miss Jean Brodie,Maggie Smith
436,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0000,7-Mar-71,1.0000,White,...,Jewish,1.0,Straight,1.0000,2006,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,The Constant Gardener,Rachel Weisz
437,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0000,20-Oct-56,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,2009,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,Slumdog Millionaire,Danny Boyle
438,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0000,26-Jul-22,1.0000,White,...,Na,1.0,Straight,1.0000,1977,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,All the President's Men,Jason Robards
439,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0000,31-Aug-28,1.0000,White,...,Na,1.0,Straight,1.0000,1999,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,Affliction,James Coburn
440,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0000,5-Aug-06,1.0000,White,...,Na,1.0,Straight,1.0000,1949,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,The Treasure of the Sierra Madre,John Huston

In [23]:
#Checking the sum of missing values in New Dataframe
print(new_df.isnull().sum())

_unit_id                          0
_golden                           0
_unit_state                       0
_trusted_judgments                0
_last_judgment_at                25
birthplace                        0
birthplace:confidence             0
date_of_birth                     0
date_of_birth:confidence          0
race_ethnicity                    0
race_ethnicity:confidence         0
religion                          0
religion:confidence               0
sexual_orientation                0
sexual_orientation:confidence     0
year_of_award                     0
year_of_award:confidence          0
award                             0
biourl                            0
movie                             0
person                            0
dtype: int64

In [24]:
#Filling in missing values for all attributes
##Using 'ffill' for _last_judgment_at and 'bfill' for religion
new_df[['_last_judgment_at']].fillna(method='bfill', inplace = True)
new_df[['religion']].fillna(method='ffill', inplace = True)
new_df.head(441)

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,religion,religion:confidence,sexual_orientation,sexual_orientation:confidence,year_of_award,year_of_award:confidence,award,biourl,movie,person
0,670454353,False,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1.0000,30-Sep-1895,1.0000,White,...,Na,1.0,Straight,1.0000,1927,1.0000,Best Director,http://www.nndb.com/people/320/000043191/,Two Arabian Knights,Lewis Milestone
1,670454354,False,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1.0000,2-Feb-1886,1.0000,White,...,Na,1.0,Straight,0.6842,1930,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,The Divine Lady,Frank Lloyd
2,670454355,False,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1.0000,30-Sep-1895,1.0000,White,...,Na,1.0,Straight,1.0000,1931,0.6667,Best Director,http://www.nndb.com/people/320/000043191/,All Quiet on the Western Front,Lewis Milestone
3,670454356,False,finalized,3,2/10/15 2:04,"Chicago, Il",1.0000,23-Feb-1899,1.0000,White,...,Na,1.0,Straight,1.0000,1932,1.0000,Best Director,http://www.nndb.com/people/544/000041421/,Skippy,Norman Taurog
4,670454357,False,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1.0000,23-Apr-1894,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1933,1.0000,Best Director,http://www.nndb.com/people/292/000044160/,Bad Girl,Frank Borzage
5,670454358,False,finalized,3,2/10/15 3:50,"Glasgow, Scotland",1.0000,2-Feb-1886,1.0000,White,...,Na,1.0,Straight,1.0000,1934,1.0000,Best Director,http://www.nndb.com/people/626/000042500/,Cavalcade,Frank Lloyd
6,670454359,False,finalized,3,2/10/15 2:07,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1935,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,It Happened One Night,Frank Capra
7,670454360,False,finalized,3,2/10/15 1:46,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1936,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,The Informer,John Ford
8,670454361,False,finalized,3,2/10/15 1:47,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1937,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,Mr. Deeds Goes to Town,Frank Capra
9,670454362,False,finalized,3,2/10/15 2:05,"Los Angeles, Ca",1.0000,3-Oct-1898,1.0000,White,...,Na,1.0,Straight,1.0000,1938,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,The Awful Truth,Leo McCarey
10,670454363,False,finalized,3,2/10/15 2:04,"Bisacquino, Sicily, Italy",1.0000,18-May-1897,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1939,1.0000,Best Director,http://www.nndb.com/people/459/000032363/,You Can't Take It with You,Frank Capra
11,670454364,False,finalized,3,2/10/15 2:10,"Pasadena, Ca",1.0000,23-Feb-1883,1.0000,White,...,Na,1.0,Straight,1.0000,1940,1.0000,Best Director,http://www.nndb.com/people/416/000041293/,Gone with the Wind,Victor Fleming
12,670454365,False,finalized,3,2/10/15 2:12,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1941,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,The Grapes of Wrath,John Ford
13,670454366,False,finalized,3,2/10/15 2:02,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1942,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,How Green Was My Valley,John Ford
14,670454367,False,finalized,3,2/10/15 3:57,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,1.0000,White,...,Na,1.0,Straight,1.0000,1943,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,Mrs. Miniver,William Wyler
15,670454368,False,finalized,3,2/10/15 2:02,"Budapest, Hungary",1.0000,24-Dec-1886,1.0000,White,...,Na,1.0,Straight,1.0000,1944,1.0000,Best Director,http://www.nndb.com/people/676/000032580/,Casablanca,Michael Curtiz
16,670454369,False,finalized,3,2/10/15 2:29,"Los Angeles, Ca",1.0000,3-Oct-1898,1.0000,White,...,Na,1.0,Straight,1.0000,1945,1.0000,Best Director,http://www.nndb.com/people/380/000044248/,Going My Way,Leo McCarey
17,670454370,False,finalized,3,2/10/15 1:55,New York City,1.0000,11-Oct-18,1.0000,White,...,Jewish,1.0,Gay,1.0000,1962,1.0000,Best Director,http://www.nndb.com/people/281/000064089/,West Side Story,Jerome Robbins
18,670454371,False,finalized,3,2/10/15 4:02,"Sucha, Galicia, Austria",0.6667,22-Jun-06,1.0000,White,...,Jewish,1.0,Straight,1.0000,1946,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,The Lost Weekend,Billy Wilder
19,670454372,False,finalized,3,2/10/15 2:12,"Mulhouse, Haut-Rhin, Alsace, France",1.0000,1-Jul-1902,1.0000,White,...,Na,1.0,Straight,1.0000,1947,1.0000,Best Director,http://www.nndb.com/people/463/000032367/,The Best Years of Our Lives,William Wyler
20,670454373,False,finalized,3,2/10/15 1:46,"Istanbul, Turkey",1.0000,7-Sep-09,1.0000,White,...,Na,1.0,Straight,1.0000,1948,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,Gentleman's Agreement,Elia Kazan
21,670454374,True,golden,82,NaN,"Nevada, Mo",1.0000,5-Aug-06,1.0000,White,...,Na,1.0,Straight,1.0000,1949,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,The Treasure of the Sierra Madre,John Huston
22,670454375,False,finalized,3,2/10/15 3:50,"Wilkes-Barre, Pa",1.0000,11-Feb-09,1.0000,White,...,Jewish,1.0,Straight,1.0000,1950,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,A Letter to Three Wives,Joseph L. Mankiewicz
23,670454376,False,finalized,3,2/10/15 1:51,"Wilkes-Barre, Pa",1.0000,11-Feb-09,1.0000,White,...,Jewish,1.0,Straight,1.0000,1951,1.0000,Best Director,http://www.nndb.com/people/723/000032627/,All About Eve,Joseph L. Mankiewicz
24,670454377,False,finalized,3,2/10/15 2:15,"Oakland, Ca",1.0000,18-Dec-04,1.0000,White,...,Na,1.0,Straight,1.0000,1952,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,A Place in the Sun,George Stevens
25,670454378,False,finalized,3,2/10/15 2:15,"Cape Elizabeth, Me",1.0000,1-Feb-1894,1.0000,White,...,Roman Catholic,1.0,Bisexual,1.0000,1953,1.0000,Best Director,http://www.nndb.com/people/458/000032362/,The Quiet Man,John Ford
26,670454379,False,finalized,3,2/10/15 1:57,"Vienna, Austria",1.0000,29-Apr-07,1.0000,White,...,Jewish,1.0,Straight,1.0000,1954,1.0000,Best Director,http://www.nndb.com/people/538/000032442/,From Here to Eternity,Fred Zinnemann
27,670454380,False,finalized,3,2/10/15 3:50,"Istanbul, Turkey",1.0000,7-Sep-09,1.0000,White,...,Na,1.0,Straight,1.0000,1955,1.0000,Best Director,http://www.nndb.com/people/537/000026459/,On the Waterfront,Elia Kazan
28,670454381,False,finalized,3,2/10/15 3:53,"Lawrence, Ks",1.0000,30-Jan-20,1.0000,White,...,Presbyterian,1.0,Straight,1.0000,1956,1.0000,Best Director,http://www.nndb.com/people/384/000044252/,Marty,Delbert Mann
29,670454382,False,finalized,3,2/10/15 3:50,"Oakland, Ca",1.0000,18-Dec-04,1.0000,White,...,Na,1.0,Straight,1.0000,1957,1.0000,Best Director,http://www.nndb.com/people/382/000044250/,Giant,George Stevens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,670454764,True,golden,86,NaN,"Woodlawn, Md",1.0000,11-Dec-67,0.9631,Black,...,Na,1.0,Straight,1.0000,2010,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,Precious,Mo'Nique
412,670454765,False,finalized,3,2/10/15 1:56,New York City,1.0000,14-Sep-60,1.0000,White,...,Na,1.0,Straight,1.0000,2011,1.0000,Best Supporting Actress,http://www.nndb.com/people/327/000042201/,The Fighter,Melissa Leo
413,670454766,False,finalized,3,2/10/15 2:18,"Montgomery, Al",1.0000,25-May-72,1.0000,Black,...,Na,1.0,Na,1.0000,2012,1.0000,Best Supporting Actress,http://www.nndb.com/people/304/000281458/,The Help,Octavia Spencer
414,670454767,False,finalized,3,2/10/15 2:18,"Brooklyn, Ny",1.0000,12-Nov-82,1.0000,White,...,Christian,1.0,Straight,1.0000,2013,1.0000,Best Supporting Actress,http://www.nndb.com/people/220/000032124/,Les MisÃŒÂ©rables,Anne Hathaway
415,670454768,False,finalized,3,2/10/15 2:10,"Mexico City, Mexico",1.0000,1-Mar-83,1.0000,Black,...,Na,1.0,Na,1.0000,2014,1.0000,Best Supporting Actress,http://www.nndb.com/people/570/000380427/,12 Years a Slave,Lupita Nyong'o
416,670927629,False,finalized,3,2/10/15 2:02,"Sucha, Galicia, Austria",1.0000,22-Jun-06,1.0000,White,...,Jewish,1.0,Straight,1.0000,1961,1.0000,Best Director,http://www.nndb.com/people/982/000024910/,The Apartment,Billy Wilder
417,670939613,False,finalized,3,2/10/15 1:53,"Independence, Mo",1.0000,16-Jul-11,1.0000,White,...,Christian Science,1.0,Straight,1.0000,1941,1.0000,Best Actress,http://www.nndb.com/people/635/000043506/,Kitty Foyle,Ginger Rogers
418,670944094,False,finalized,3,2/10/15 2:18,"Concord, Ca",1.0000,9-Jul-56,1.0000,White,...,Born-Again Christian,1.0,Straight,1.0000,1994,1.0000,Best Actor,http://www.nndb.com/people/687/000022621/,Philadelphia,Tom Hanks
419,670944168,False,finalized,3,2/10/15 3:55,New York City,1.0000,3-Feb-39,1.0000,White,...,Na,1.0,Straight,1.0000,1979,0.6667,Best Director,http://www.nndb.com/people/810/000043681/,The Deer Hunter,Michael Cimino
420,670944316,False,finalized,3,2/10/15 2:05,"Quincy, Il",1.0000,3-May-06,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1942,1.0000,Best Supporting Actress,http://www.nndb.com/people/690/000042564/,The Great Lie,Mary Astor
421,670944478,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,4-Jun-75,1.0000,White,...,Buddhist,1.0,Bisexual,1.0000,2000,1.0000,Best Supporting Actress,http://www.nndb.com/people/493/000023424/,"Girl, Interrupted",Angelina Jolie
422,670944543,False,finalized,3,2/10/15 2:12,New York City,1.0000,31-Oct-27,1.0000,White,...,Jewish,1.0,Straight,1.0000,1976,1.0000,Best Supporting Actress,http://www.nndb.com/people/409/000032313/,Shampoo,Lee Grant
423,670944623,False,finalized,3,2/10/15 2:11,New York City,1.0000,25-Jun-1903,1.0000,White,...,Na,1.0,Straight,1.0000,1946,1.0000,Best Supporting Actress,http://www.nndb.com/people/081/000063889/,National Velvet,Anne Revere
424,670944674,False,finalized,3,2/10/15 2:05,"Bascom, Fl",1.0000,14-Jan-41,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1977,1.0000,Best Actress,http://www.nndb.com/people/884/000022818/,Network,Faye Dunaway
425,670944755,False,finalized,3,2/10/15 2:04,"Walters, Ok",1.0000,13-Dec-10,1.0000,White,...,Na,1.0,Straight,1.0000,1943,1.0000,Best Supporting Actor,http://www.nndb.com/people/680/000042554/,Johnny Eager,Van Heflin
426,670944822,False,finalized,3,2/10/15 4:14,"Thomasville, Ga",1.0000,27-Feb-30,1.0000,White,...,Na,1.0,Straight,1.0000,1958,1.0000,Best Actress,http://www.nndb.com/people/747/000043618/,The Three Faces of Eve,Joanne Woodward
427,670944835,False,finalized,3,2/10/15 2:08,"Helena, Mt",1.0000,7-May-1901,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,1953,1.0000,Best Actor,http://www.nndb.com/people/740/000031647/,High Noon,Gary Cooper
428,670944920,False,finalized,3,2/10/15 3:58,"London, England",1.0000,27-Feb-32,1.0000,White,...,Jewish,1.0,Straight,1.0000,1967,1.0000,Best Actress,http://www.nndb.com/people/624/000023555/,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,670944948,False,finalized,3,2/10/15 2:06,"Lincoln, Ne",1.0000,30-Jul-74,1.0000,White,...,Na,1.0,Straight,1.0000,2005,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,Million Dollar Baby,Hilary Swank
430,670945043,True,golden,86,NaN,"Lincoln, Ne",1.0000,30-Jul-74,1.0000,White,...,Na,1.0,Straight,1.0000,2005,1.0000,Best Actress,http://www.nndb.com/people/333/000026255/,Million Dollar Baby,Hilary Swank
431,670945693,False,finalized,3,2/10/15 1:49,"Los Angeles, Ca",1.0000,27-Sep-72,1.0000,White,...,Jewish,1.0,Straight,1.0000,1999,1.0000,Best Actress,http://www.nndb.com/people/592/000023523/,Shakespeare in Love,Gwyneth Paltrow
432,670945790,False,finalized,3,2/10/15 2:08,"Malden, Ma",1.0000,16-Jun-07,1.0000,White,...,Na,1.0,Na,1.0000,1969,1.0000,Best Supporting Actor,http://www.nndb.com/people/559/000049412/,The Subject Was Roses,Jack Albertson
433,670945834,False,finalized,3,2/10/15 2:07,"Woodlawn, Md",1.0000,11-Dec-67,1.0000,Black,...,Na,1.0,Straight,1.0000,2010,1.0000,Best Supporting Actress,http://www.nndb.com/people/836/000131443/,Precious,Mo'Nique
434,670945895,False,finalized,3,2/10/15 2:13,"La Jolla, Ca",1.0000,14-Aug-59,1.0000,White,...,Na,1.0,Straight,1.0000,2001,1.0000,Best Supporting Actress,http://www.nndb.com/people/641/000025566/,Pollock,Marcia Gay Harden
435,670946199,False,finalized,3,2/10/15 2:03,"Ilford, Essex, England",1.0000,28-Dec-34,1.0000,White,...,Na,1.0,Straight,1.0000,1970,1.0000,Best Actress,http://www.nndb.com/people/260/000030170/,The Prime of Miss Jean Brodie,Maggie Smith
436,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0000,7-Mar-71,1.0000,White,...,Jewish,1.0,Straight,1.0000,2006,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,The Constant Gardener,Rachel Weisz
437,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0000,20-Oct-56,1.0000,White,...,Roman Catholic,1.0,Straight,1.0000,2009,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,Slumdog Millionaire,Danny Boyle
438,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0000,26-Jul-22,1.0000,White,...,Na,1.0,Straight,1.0000,1977,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,All the President's Men,Jason Robards
439,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0000,31-Aug-28,1.0000,White,...,Na,1.0,Straight,1.0000,1999,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,Affliction,James Coburn
440,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0000,5-Aug-06,1.0000,White,...,Na,1.0,Straight,1.0000,1949,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,The Treasure of the Sierra Madre,John Huston

In [21]:
#Finding duplicate rows
dup_df=new_df[new_df.duplicated()]
print('There are ', dup_df.shape, 'duplicate rows')

There are  (0, 21) duplicate rows

In [28]:
#Bucketing year_of_award 
year_award_label = ['New', 'Old', 'Too Old']
category = [1850,1900,2000,2020]
new_df['year_of_award_label'] = pd.cut(new_df['year_of_award'], labels=year_award_label, bins=category, include_lowest = False)
print(new_df[['year_of_award','year_of_award_label']])

     year_of_award year_of_award_label
0             1927                 Old
1             1930                 Old
2             1931                 Old
3             1932                 Old
4             1933                 Old
5             1934                 Old
6             1935                 Old
7             1936                 Old
8             1937                 Old
9             1938                 Old
10            1939                 Old
11            1940                 Old
12            1941                 Old
13            1942                 Old
14            1943                 Old
15            1944                 Old
16            1945                 Old
17            1962                 Old
18            1946                 Old
19            1947                 Old
20            1948                 Old
21            1949                 Old
22            1950                 Old
23            1951                 Old
24            1952                 Old
25            1953                 Old
26            1954                 Old
27            1955                 Old
28            1956                 Old
29            1957                 Old
..             ...                 ...
411           2010             Too Old
412           2011             Too Old
413           2012             Too Old
414           2013             Too Old
415           2014             Too Old
416           1961                 Old
417           1941                 Old
418           1994                 Old
419           1979                 Old
420           1942                 Old
421           2000                 Old
422           1976                 Old
423           1946                 Old
424           1977                 Old
425           1943                 Old
426           1958                 Old
427           1953                 Old
428           1967                 Old
429           2005             Too Old
430           2005             Too Old
431           1999                 Old
432           1969                 Old
433           2010             Too Old
434           2001             Too Old
435           1970                 Old
436           2006             Too Old
437           2009             Too Old
438           1977                 Old
439           1999                 Old
440           1949                 Old

[441 rows x 2 columns]

In [34]:
#Bucketing birthplace_confidence
birthplace_label = ['Unsure', 'Sure']
category = [0.,.99,1.]
new_df['birthplace:confidence_label'] = pd.cut(new_df['birthplace:confidence'], labels=birthplace_label, bins=category, include_lowest = False)

print(new_df[['birthplace:confidence','birthplace:confidence_label']])

     birthplace:confidence birthplace:confidence_label
0                   1.0000                        Sure
1                   1.0000                        Sure
2                   1.0000                        Sure
3                   1.0000                        Sure
4                   1.0000                        Sure
5                   1.0000                        Sure
6                   1.0000                        Sure
7                   1.0000                        Sure
8                   1.0000                        Sure
9                   1.0000                        Sure
10                  1.0000                        Sure
11                  1.0000                        Sure
12                  1.0000                        Sure
13                  1.0000                        Sure
14                  1.0000                        Sure
15                  1.0000                        Sure
16                  1.0000                        Sure
17                  1.0000                        Sure
18                  0.6667                      Unsure
19                  1.0000                        Sure
20                  1.0000                        Sure
21                  1.0000                        Sure
22                  1.0000                        Sure
23                  1.0000                        Sure
24                  1.0000                        Sure
25                  1.0000                        Sure
26                  1.0000                        Sure
27                  1.0000                        Sure
28                  1.0000                        Sure
29                  1.0000                        Sure
..                     ...                         ...
411                 1.0000                        Sure
412                 1.0000                        Sure
413                 1.0000                        Sure
414                 1.0000                        Sure
415                 1.0000                        Sure
416                 1.0000                        Sure
417                 1.0000                        Sure
418                 1.0000                        Sure
419                 1.0000                        Sure
420                 1.0000                        Sure
421                 1.0000                        Sure
422                 1.0000                        Sure
423                 1.0000                        Sure
424                 1.0000                        Sure
425                 1.0000                        Sure
426                 1.0000                        Sure
427                 1.0000                        Sure
428                 1.0000                        Sure
429                 1.0000                        Sure
430                 1.0000                        Sure
431                 1.0000                        Sure
432                 1.0000                        Sure
433                 1.0000                        Sure
434                 1.0000                        Sure
435                 1.0000                        Sure
436                 1.0000                        Sure
437                 1.0000                        Sure
438                 1.0000                        Sure
439                 1.0000                        Sure
440                 1.0000                        Sure

[441 rows x 2 columns]

In [ ]:
#Attempting to create a boxplot
import seaborn as sns
import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt  
%matplotlib inline

sns.set(style="whitegrid")
new_df.boxplot(by='_trusted_judgments', grid = True)

In [ ]:
#Attempt 2 to create a boxplot
import seaborn as sns

sns.boxplot(x=['_trusted_judgments'], color='lime')

In [ ]:
#Looking in to an attribute for outlier
print(new_df[['person', 'movie', '_trusted_judgments']].iloc[new_df['_trusted_judgments'].idxmax()])

In [ ]:
#Describe that attribute
print(new_df['_trusted_judgments'].describe())

In [ ]:
#Checking data type to calculate z-score
print(new_df.dtypes)

In [ ]:
#Creating new dataframe with only int or float attributes
NOb_df=new_df.select_dtypes(exclude=['object', 'bool', 'category'])
print(NOb_df.shape)

In [ ]:
#Calculate z-score to get rid of outliers
import numpy as np 
from scipy import stats

df_zscore=NOb_df[(np.abs(stats.zscore(NOb_df))<=3).all(axis=1)]

In [ ]:
#New boxplot
sns.boxplot(x=df_zscore['_trusted_judgments'], color='lime')